# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telophasecli < Formula
  desc "Open-Source AWS Control Tower"
  homepage "https://github.com/Santiago-Labs/telophasecli"
  version "0.7.12"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.7.12/telophasecli_Darwin_x86_64.tar.gz"
      sha256 "4584d9c5a43328fb034ddcb19511c06b4f98faceb7e20a1427bb2411c80be8e6"

      def install
        bin.install "telophasecli"
      end
    end
    on_arm do
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.7.12/telophasecli_Darwin_arm64.tar.gz"
      sha256 "b3937c3a1716429ec669fb3b4b00e4998086617faeaff30430ef654dd3a27070"

      def install
        bin.install "telophasecli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.7.12/telophasecli_Linux_x86_64.tar.gz"
        sha256 "e0a53ef32d17cfe31df9109dd4885a5e98a46f7f0c91d1c89931ca3297d33096"

        def install
          bin.install "telophasecli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.7.12/telophasecli_Linux_arm64.tar.gz"
        sha256 "2d9e1dbb8a634cf8b35597d7cb63702c7f86015517f869992b956273d3117e47"

        def install
          bin.install "telophasecli"
        end
      end
    end
  end
end
